# Site settings
author: Victoria Fluharty
title: Torrnado's Coding Adventures
header-img: img/color_splash.jpg
email: victoria.fluharty@gmail.com
copyright_name: Victoria Fluharty
description: > # this means to ignore newlines until "baseurl:"
  Join me on my journey of becoming a web developer!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username:
github_username:  torianne02

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
