# Site settings
title: 
header-img: img/home-bg.png
email: victoria.fluharty@gmail.com
copyright_name: torianne02
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  torianne02
learn_profile: torianne02
email_username: victoria.fluharty@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
